//
//  TrackerHelper.h
//  Google-Analytics-for-OS-X-macOS
//
//  Created by Splenden on 2018/2/21.
//

#import <Foundation/Foundation.h>

@interface TrackerHelper : NSObject
/**
 * When iOS, generated by UIDevice identifierForVendor, which will change when app re-install. OSX, generated by device serial number and user name.
 * @see: http://www.cocoachina.com/industry/20130422/6040.html
 */
- (NSString * _Nonnull)userIdentifier;
/**
 * Gnerated by executing javascript `navigator.userAgent` on UI_WebView(iOS)\WebView(OSX)
 */
- (NSString * _Nonnull)userAgentString;
/**
 * Returns screen size and preferred language
 **/
- (NSString * _Nonnull)systemInfo;
/**
 * Generated by NSBundle kCFBundleNameKey
 **/
- (NSString * _Nonnull)applicationName;
/**
 * Generated by NSBundle CFBundleVersion
 **/
- (NSString * _Nonnull)applicationVersion;
@end
